### ISSUE TITLE
m3usync.py - ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by Porco-Rosso** [kellertobias/m3u-sync#1]
Hi, 

Thanks again for the tool!
 I am trying to run m3usync.py, but get the following error:

```
[info] mysql started
weakly-referenced object no longer exists
Traceback (most recent call last):
  File "/root/m3usync/m3usync.py", line 11, in <module>
    sql.execute('DELETE FROM playlist WHERE m3ufile IS NOT NULL')
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 484, in execute
    if not self._connection:
ReferenceError: weakly-referenced object no longer exists
```

I had a bit of an issue getting  the error `ImportError: No module named 'mysql'` until I ran `apt-get install python3-mysql.connector`. Now I am experiencing the error above. I'm not familiar with python, so I would appreciate any pointers.

**Comment by kellertobias** [comment]
Whoops, seems that I've pushed an old version of the file, the actual sync-handling isn't there...

however the error should also not be there. I'll check it out till monday and let you know

**Comment by kellertobias** [comment]
I've updated the file to be the newest version.

**Comment by Porco-Rosso** [comment]
Thanks, after some tweaking I finally got it to work!

**Comment by kellertobias** [comment]
what was your "tweaking"? Perhaps I could add that to the readme
mit freundlichen Grüßen
*Tobias Keller*


Am Mo., 10. Dez. 2018 um 14:23 Uhr schrieb Porco Rosso <
notifications@github.com>:

**Comment by Porco-Rosso** [comment]
Firstly, the sql connector line, so the obvious password, database etc.
`sql = mysql.connector.connect(host='localhost', database='databaseforkoel', user='koel', password='password')`

The more tricky part was figuring out what combination was needed for lines
`for m3upath in glob.glob("/mnt/music/iTunes Media/Music/*.m3u8"):`
and for 
`songPath = path.join("/mnt/music/iTunes Media/Music", songPath.strip())`

Lastly, I realized that my files were named m3u8 not m3u, so needed to edit any references.

Didn't have to do any fiddling with python packages or dependencies this time, but can't say if it is because of the commands I mentioned previously worked or not.
