### ISSUE TITLE
m3usync - for multiple users

### ISSUE THREAD

**Issue by Porco-Rosso** [kellertobias/m3u-sync#2]
Hi, thanks again for the extremely useful script. It has been working without issue for months now.
I recently added some guest accounts to my Koel install, and was wondering how I would need to modify the script in order to insert the playlists into the database for multiple accounts, and not just the main 'admin' account. I've tried poking around a little bit, but my knowledge of sql and the database structure is weak.
Any pointers?

**Comment by kellertobias** [comment]
sadly i have chosen to change the way how I have managed music and so no longer use koel.

However, I checked how the database looks like and it seems that koel has one playlist per user (see https://github.com/kellertobias/m3u-sync/blob/master/koel/m3usync/m3usync.py#L32). What you could do is to wrap the whole script (line 17 up to 57) in a function, e.g.

```python
def sync_for_user(userId):
    for m3upath in .......
```

and then call this function per userId (which you could either fetch from the SQL Database or simply put hardcoded in an array).

PS.: You could provide a merge request, if you want to.

**Comment by Porco-Rosso** [comment]
Hi, sorry for the long response time. I got the playlists to sync for the other users by incrementing the userId in a hardcoded way. I will try to wrap them in a function when I have time so it can all be in one script. Thanks for the tip on the function format.

**Comment by Porco-Rosso** [comment]
I successfully wrapped the function and it works with multiple users, I just don't have the time to generalize the script for other's use. So closing this issue. Thanks for the help.
